{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fpp3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fpp3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fpp3/fpp3_{{ version }}.tar.gz
  sha256: 3245c18d52f35f5ac3e706732121d0a8bf0f8472b996464e3ad1ebd023a56f96

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-dplyr >=0.7.4
    - r-fable >=0.3.0
    - r-fabletools >=0.3.0
    - r-feasts >=0.1.7
    - r-ggplot2 >=3.1.1
    - r-lubridate >=1.7.4
    - r-purrr >=0.2.4
    - r-rstudioapi >=0.7
    - r-tibble >=1.4.2
    - r-tidyr >=0.8.3
    - r-tsibble >=0.9.3
    - r-tsibbledata >=0.2.0
  run:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-dplyr >=0.7.4
    - r-fable >=0.3.0
    - r-fabletools >=0.3.0
    - r-feasts >=0.1.7
    - r-ggplot2 >=3.1.1
    - r-lubridate >=1.7.4
    - r-purrr >=0.2.4
    - r-rstudioapi >=0.7
    - r-tibble >=1.4.2
    - r-tidyr >=0.8.3
    - r-tsibble >=0.9.3
    - r-tsibbledata >=0.2.0

test:
  commands:
    - $R -e "library('fpp3')"           # [not win]
    - "\"%R%\" -e \"library('fpp3')\""  # [win]

about:
  home: https://OTexts.com/fpp3/
  dev_url: https://github.com/robjhyndman/fpp3package
  doc_url: https://pkg.robjhyndman.com/fpp3package/
  license: GPL-3.0-only
  summary: 'All data sets required for the examples and exercises in the book "Forecasting: principles
    and practice" by Rob J Hyndman and George Athanasopoulos <https://OTexts.com/fpp3/>.
    All packages required to run the examples are also loaded. Additional data sets
    not used in the book are also included.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - cnrrobertson

# Package: fpp3
# Title: Data for "Forecasting: Principles and Practice" (3rd Edition)
# Version: 1.0.0
# Authors@R: c(person(given = "Rob", family = "Hyndman", role = c("aut", "cre", "cph"), email = "Rob.Hyndman@monash.edu", comment = c(ORCID = "0000-0002-2140-5352")), person(given = "George", family = "Athanasopoulos", role = "ctb"), person(given = "Mitchell", family = "O'Hara-Wild", role = "ctb"), person(given = "Nuwani", family = "Palihawadana", role = "ctb"), person(given = "Shanika", family = "Wickramasuriya", role = "ctb"), person(given = "RStudio", role = c("cph")))
# Description: All data sets required for the examples and exercises in the book "Forecasting: principles and practice" by Rob J Hyndman and George Athanasopoulos <https://OTexts.com/fpp3/>. All packages required to run the examples are also loaded. Additional data sets not used in the book are also included.
# License: GPL-3
# URL: https://pkg.robjhyndman.com/fpp3package/, https://github.com/robjhyndman/fpp3package, https://OTexts.com/fpp3/
# BugReports: https://github.com/robjhyndman/fpp3package/issues
# Depends: R (>= 4.1.0)
# Imports: cli (>= 1.0.0), crayon (>= 1.3.4), dplyr (>= 0.7.4), fable (>= 0.3.0), fabletools (>= 0.3.0), feasts (>= 0.1.7), ggplot2 (>= 3.1.1), lubridate (>= 1.7.4), purrr (>= 0.2.4), rstudioapi (>= 0.7), tibble (>= 1.4.2), tidyr (>= 0.8.3), tsibble (>= 0.9.3), tsibbledata (>= 0.2.0)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.3.1
# NeedsCompilation: no
# Packaged: 2024-06-25 08:35:05 UTC; hyndman
# Author: Rob Hyndman [aut, cre, cph] (<https://orcid.org/0000-0002-2140-5352>), George Athanasopoulos [ctb], Mitchell O'Hara-Wild [ctb], Nuwani Palihawadana [ctb], Shanika Wickramasuriya [ctb], RStudio [cph]
# Maintainer: Rob Hyndman <Rob.Hyndman@monash.edu>
# Repository: CRAN
# Date/Publication: 2024-06-25 08:50:01 UTC
